### ISSUE TITLE
reagent 0.7.0

### ISSUE THREAD

**Issue by NeCkEr** [ElChache/universal-reframe#1]
Can't get this running with any new versions of reagent...

```
/universal-reframe/target/server_dev/create-react-class.inc.js:764
var ReactNoopUpdateQueue = new React.Component().updater;
                                                ^
ReferenceError: React is not defined
```

**Comment by ElChache** [comment]
Thanks for the heads up! From the Reagent CHANGES.md file on version 7.0:

React updated to 15.5.4 (#292)
 - Uses create-react-class instead of deprecated React.createClass
 - Reagent has now dependency on cljsjs/create-react-class, if you are using other methods to provide React, you need to exclude this Cljsjs dependency and provide the library yourself.

I'm sure it is related to that, I'll take a look into it ASAP. I want it to work also with reagent 8

**Comment by ElChache** [comment]
It works now with Reagent 8. It requires react 16, and no more hacks are needed on index-dev.js.
